#!/usr/bin/env python
# -*- coding=utf-8 -*-

# Author: Ryan Henrichson
# Version: 0.1
# Date: 09/02/2026
# Description: Reference data tables for d20 FuturePath spaceship sheets

import logging

from FuturePathAPI.libs.ReferenceData import get_reference_db

log = logging.getLogger("SpaceShipReferenceData")

HULL_SIZES = [
    {
        "Name": "Fine",
        "TrackingDC": 12,
        "SizeMod": 2,
        "DetectionDC": 12,
        "BattleDamageCapacity": 0,
        "SqFt": "<75 ft / 256 per sq",
        "PassengerCapacity": 1,
        "AvgWeight": "~4 Tons",
        "CargoCapacity": 4,
        "CustBonus": 0,
        "MilitaryCost": "$240,000",
        "MilitaryProcureDiff": 0,
        "MilitaryHardPoints": 2,
        "MilitaryBays": 0,
        "CivilianCost": "$80,000",
        "CivilianProcureDiff": 0,
        "CivilianHardPoints": 1,
        "CivilianBays": 1,
        "WeaponBaySize": "Small",
    },
    {
        "Name": "Diminutive",
        "TrackingDC": 12,
        "SizeMod": 2,
        "DetectionDC": 11,
        "BattleDamageCapacity": 1,
        "SqFt": "~125 ft / 16 per sq",
        "PassengerCapacity": 2,
        "AvgWeight": "~16 Tons",
        "CargoCapacity": 16,
        "CustBonus": 0,
        "MilitaryCost": "$480,000",
        "MilitaryProcureDiff": 1,
        "MilitaryHardPoints": 3,
        "MilitaryBays": 0,
        "CivilianCost": "$160,000",
        "CivilianProcureDiff": 0,
        "CivilianHardPoints": 2,
        "CivilianBays": 2,
        "WeaponBaySize": "Small",
    },
    {
        "Name": "Tiny",
        "TrackingDC": 11,
        "SizeMod": 1,
        "DetectionDC": 10,
        "BattleDamageCapacity": 2,
        "SqFt": "~500+ ft / ~1 sq",
        "PassengerCapacity": 4,
        "AvgWeight": "~64 Tons",
        "CargoCapacity": 64,
        "CustBonus": 1,
        "MilitaryCost": "$1.9 Million",
        "MilitaryProcureDiff": 1,
        "MilitaryHardPoints": 5,
        "MilitaryBays": 1,
        "CivilianCost": "$640,000",
        "CivilianProcureDiff": 0,
        "CivilianHardPoints": 3,
        "CivilianBays": 4,
        "WeaponBaySize": "Small",
    },
    {
        "Name": "Small",
        "TrackingDC": 11,
        "SizeMod": 1,
        "DetectionDC": 9,
        "BattleDamageCapacity": 2,
        "SqFt": "~2,000+ ft / ~4 sq",
        "PassengerCapacity": 8,
        "AvgWeight": "~256 Tons",
        "CargoCapacity": 250,
        "CustBonus": 1,
        "MilitaryCost": "$12 Million",
        "MilitaryProcureDiff": 1,
        "MilitaryHardPoints": 6,
        "MilitaryBays": 2,
        "CivilianCost": "$4 Million",
        "CivilianProcureDiff": 0,
        "CivilianHardPoints": 4,
        "CivilianBays": 5,
        "WeaponBaySize": "Medium",
    },
    {
        "Name": "Medium",
        "TrackingDC": 10,
        "SizeMod": 0,
        "DetectionDC": 9,
        "BattleDamageCapacity": 3,
        "SqFt": "~4,000+ ft / ~8 sq",
        "PassengerCapacity": 16,
        "AvgWeight": "~512 Tons",
        "CargoCapacity": 510,
        "CustBonus": 1,
        "MilitaryCost": "$36 Million",
        "MilitaryProcureDiff": 2,
        "MilitaryHardPoints": 6,
        "MilitaryBays": 3,
        "CivilianCost": "$12 Million",
        "CivilianProcureDiff": 0,
        "CivilianHardPoints": 4,
        "CivilianBays": 6,
        "WeaponBaySize": "Medium",
    },
    {
        "Name": "Large",
        "TrackingDC": 9,
        "SizeMod": -1,
        "DetectionDC": 9,
        "BattleDamageCapacity": 3,
        "SqFt": "~8,000+ ft / ~16 sq",
        "PassengerCapacity": 32,
        "AvgWeight": "~1,024 Tons",
        "CargoCapacity": 1000,
        "CustBonus": 2,
        "MilitaryCost": "$108 Million",
        "MilitaryProcureDiff": 2,
        "MilitaryHardPoints": 7,
        "MilitaryBays": 4,
        "CivilianCost": "$36 Million",
        "CivilianProcureDiff": 1,
        "CivilianHardPoints": 5,
        "CivilianBays": 7,
        "WeaponBaySize": "Large",
    },
    {
        "Name": "Huge",
        "TrackingDC": 9,
        "SizeMod": -1,
        "DetectionDC": 8,
        "BattleDamageCapacity": 4,
        "SqFt": "~32,000+ ft / ~64 sq",
        "PassengerCapacity": 120,
        "AvgWeight": "~4,096 Tons",
        "CargoCapacity": 4000,
        "CustBonus": 2,
        "MilitaryCost": "$324 Million",
        "MilitaryProcureDiff": 3,
        "MilitaryHardPoints": 8,
        "MilitaryBays": 5,
        "CivilianCost": "$108 Million",
        "CivilianProcureDiff": 2,
        "CivilianHardPoints": 6,
        "CivilianBays": 8,
        "WeaponBaySize": "Large",
    },
    {
        "Name": "Gargantuan",
        "TrackingDC": 8,
        "SizeMod": -2,
        "DetectionDC": 7,
        "BattleDamageCapacity": 4,
        "SqFt": "~128,000+ ft / ~256 sq",
        "PassengerCapacity": 500,
        "AvgWeight": "~16,384 Tons",
        "CargoCapacity": 16000,
        "CustBonus": 2,
        "MilitaryCost": "$972 Million",
        "MilitaryProcureDiff": 3,
        "MilitaryHardPoints": 9,
        "MilitaryBays": 7,
        "CivilianCost": "$324 Million",
        "CivilianProcureDiff": 3,
        "CivilianHardPoints": 7,
        "CivilianBays": 9,
        "WeaponBaySize": "Huge",
    },
    {
        "Name": "Colossal",
        "TrackingDC": 8,
        "SizeMod": -2,
        "DetectionDC": 6,
        "BattleDamageCapacity": 5,
        "SqFt": "~512,000+ ft / ~1,024 sq",
        "PassengerCapacity": 2000,
        "AvgWeight": "~65,536 Tons",
        "CargoCapacity": 65000,
        "CustBonus": 3,
        "MilitaryCost": "$2.9 Billion",
        "MilitaryProcureDiff": 4,
        "MilitaryHardPoints": 10,
        "MilitaryBays": 8,
        "CivilianCost": "$972 Million",
        "CivilianProcureDiff": 4,
        "CivilianHardPoints": 8,
        "CivilianBays": 10,
        "WeaponBaySize": "Huge",
    },
]

HULL_CONFIGURATIONS = [
    {
        "Name": "Barges",
        "Description": "The 'pack mule' of the galaxy. Common cargo transport vessel found everywhere.",
        "AverageSize": "Medium (Small - Large)",
        "AverageCost": "$12 Million",
        "ProcureDiff": 0,
        "Disadvantages": "-2 to Engines, -1 to Weapons, -2 Hard Points, -1 Bay (occupied by extra Cargo Space)",
        "Advantages": "Cargo Space is one ship size modifier higher. Common bonus: -1 to Procure Diff and 50% less time/cost to repair.",
        "Mods": [
            {"Target": "Engines", "Mod": "-2"},
            {"Target": "Weapons", "Mod": "-1"},
            {"Target": "Hard_Points", "Mod": "-2"},
            {"Target": "Bays", "Mod": "-1"},
        ],
    },
    {
        "Name": "Battle Cruisers",
        "Description": "Flexible, heavy-hitting machines of war used as a counter for smaller ships and bandits.",
        "AverageSize": "Large",
        "AverageCost": "$120 Million",
        "ProcureDiff": 3,
        "Disadvantages": "Cargo Capacity is one size lower, Passenger Cap is 8, -5 Attribute Points, -1 Customization point (Minimum 1)",
        "Advantages": "+2 Electronics, +2 Engines, +1 Non-Weapon Hard Point, Can pick one Ship Function for free without taking Customization Points.",
        "Mods": [
            {"Target": "Electronics", "Mod": "+2"},
            {"Target": "Engines", "Mod": "+2"},
            {"Target": "Hard_Points", "Mod": "+1"},
            {"Target": "Customization", "Mod": "-1"},
        ],
    },
    {
        "Name": "Battle Ships",
        "Description": "Massive war machines and the backbone of militaries, built for large-scale conflict.",
        "AverageSize": "Huge (or Gargantuan)",
        "AverageCost": "$384 Million",
        "ProcureDiff": 4,
        "Disadvantages": "Cargo Capacity and Passenger Cap is one size smaller, -5 Attribute Points, -1 Customization Point (Minimum 1)",
        "Advantages": "+2 Weapons, +1 Structure, +1 Engines, Gains 'Bombard' function for free, Gains one more Ship Function of choice for free, +1 Hard Point (Weapon Only).",
        "Mods": [
            {"Target": "Weapons", "Mod": "+2"},
            {"Target": "Structure", "Mod": "+1"},
            {"Target": "Engines", "Mod": "+1"},
            {"Target": "Hard_Points", "Mod": "+1"},
            {"Target": "Customization", "Mod": "-1"},
        ],
    },
    {
        "Name": "Capital",
        "Description": "Massive command ships and super carriers acting as an entire base of operations.",
        "AverageSize": "Colossal",
        "AverageCost": "$3.2 Billion",
        "ProcureDiff": 5,
        "Disadvantages": "-5 Attribute Points, -2 Engines, -2 Hard Points, -1 Customization Point (Minimum 1)",
        "Advantages": "+1 Bays, +2 Sensors, +2 Electronics, Passenger capacity: 864, Special Position: Supreme Commander (system-wide leadership bonus), Choose any one Ship Function installed at no cost.",
        "Mods": [
            {"Target": "Bays", "Mod": "+1"},
            {"Target": "Sensors", "Mod": "+2"},
            {"Target": "Electronics", "Mod": "+2"},
            {"Target": "Engines", "Mod": "-2"},
            {"Target": "Hard_Points", "Mod": "-2"},
            {"Target": "Customization", "Mod": "-1"},
        ],
    },
    {
        "Name": "Carriers",
        "Description": "Ships that provide fleet mobility, designed to carry, deploy, and maintain smaller ships and drones.",
        "AverageSize": "Gargantuan (Huge - Colossal)",
        "AverageCost": "$1.2 Billion",
        "ProcureDiff": 4,
        "Disadvantages": "-5 Attribute Points, -2 Engines, -4 Hard Points, -1 Bay, -1 Customization Point (Minimum 1)",
        "Advantages": "+2 Sensors, +2 Electronics, Built-in Repair Facility for ships two sizes and smaller. Can hold 6 Large ships by default. Special Position: Field Commander.",
        "Mods": [
            {"Target": "Sensors", "Mod": "+2"},
            {"Target": "Electronics", "Mod": "+2"},
            {"Target": "Engines", "Mod": "-2"},
            {"Target": "Hard_Points", "Mod": "-4"},
            {"Target": "Bays", "Mod": "-1"},
            {"Target": "Customization", "Mod": "-1"},
        ],
    },
    {
        "Name": "Cruisers (Military)",
        "Description": "Flexible combat vessels used as police craft or military portal/recon.",
        "AverageSize": "Medium",
        "AverageCost": "$40 Million",
        "ProcureDiff": 2,
        "Disadvantages": "-3 Attribute Points",
        "Advantages": "+1 Hard Point or +1 Bay, +2 Engines or +2 Electronics, Pick one free Ship Function.",
        "Mods": [
            {"Target": "Hard_Points", "Mod": "+1"},
            {"Target": "Bays", "Mod": "+1"},
            {"Target": "Engines", "Mod": "+2"},
            {"Target": "Electronics", "Mod": "+2"},
        ],
    },
    {
        "Name": "Cruisers (Civilian)",
        "Description": "Demilitarized or VIP luxury cruiser hulls with upgraded accommodations.",
        "AverageSize": "Medium",
        "AverageCost": "$10 Million",
        "ProcureDiff": 0,
        "Disadvantages": "-1 Structure, -1 Hard Point, -2 Attribute Points",
        "Advantages": "+2 Engines, +2 Sensors, Luxury passenger bay (accommodates up to 16 passengers).",
        "Mods": [
            {"Target": "Engines", "Mod": "+2"},
            {"Target": "Sensors", "Mod": "+2"},
            {"Target": "Structure", "Mod": "-1"},
            {"Target": "Hard_Points", "Mod": "-1"},
        ],
    },
    {
        "Name": "Drones",
        "Description": "AI-controlled machines ranging from military swarms to personal defense units.",
        "AverageSize": "Fine (Fine - Small)",
        "AverageCost": "$100,000",
        "ProcureDiff": 0,
        "Disadvantages": "-1 across all Attributes",
        "Advantages": "Can be operated without a pilot. Swarm bonuses apply when 4+ are teamed. Requires a Drone Bay.",
        "Mods": [
            {"Target": "Weapons", "Mod": "-1"},
            {"Target": "Shields", "Mod": "-1"},
            {"Target": "Engines", "Mod": "-1"},
            {"Target": "Structure", "Mod": "-1"},
            {"Target": "Sensors", "Mod": "-1"},
            {"Target": "Electronics", "Mod": "-1"},
        ],
    },
    {
        "Name": "Destroyers",
        "Description": "Heavily armed medium combat craft designed specifically to counter smaller swarms.",
        "AverageSize": "Medium",
        "AverageCost": "$38 Million",
        "ProcureDiff": 3,
        "Disadvantages": "Illegal to own (Procure Diff +1), -3 Attribute Points, -1 Bay, Weapon Hard Points geared for 'Small' weapon size",
        "Advantages": "+2 Hard Points, All weapons considered Gimbaled (+1 Targeting), No penalties for targeting smaller craft.",
        "Mods": [
            {"Target": "Hard_Points", "Mod": "+2"},
            {"Target": "Bays", "Mod": "-1"},
        ],
    },
    {
        "Name": "Dreadnoughts",
        "Description": "Gargantuan station busters fitted with hyper-focused energy cannons.",
        "AverageSize": "Gargantuan (Huge - Colossal)",
        "AverageCost": "$3 Billion",
        "ProcureDiff": 5,
        "Disadvantages": "-2 Engines, -5 Ability Points, -4 Hard Points, -3 Bays, Cannot cloak",
        "Advantages": "Super gigantic hyper-focused energy cannon (100x Huge range, deals 24d10 * 10 damage; cooldown (1d4 + 2) - Electronics Mod rounds).",
        "Mods": [
            {"Target": "Engines", "Mod": "-2"},
            {"Target": "Hard_Points", "Mod": "-4"},
            {"Target": "Bays", "Mod": "-3"},
        ],
    },
    {
        "Name": "Fighters",
        "Description": "Agile single-pilot (or small crew) combat craft.",
        "AverageSize": "Fine - Diminutive",
        "AverageCost": "$480,000",
        "ProcureDiff": 1,
        "Disadvantages": "-2 Structure, Passenger Cap is 1",
        "Advantages": "+2 Engines, Gains Feint Ship Function for free.",
        "Mods": [
            {"Target": "Engines", "Mod": "+2"},
            {"Target": "Structure", "Mod": "-2"},
        ],
    },
    {
        "Name": "Frigates",
        "Description": "Common police craft or VIP transport throughout the Ring.",
        "AverageSize": "Small (Small - Medium)",
        "AverageCost": "$4 - $36 Million",
        "ProcureDiff": 0,
        "Disadvantages": "-1 to Weapons",
        "Advantages": "+1 to Sensors, +1 Attribute Point, 50% less cost/time spent on repairs.",
        "Mods": [
            {"Target": "Sensors", "Mod": "+1"},
            {"Target": "Weapons", "Mod": "-1"},
        ],
    },
    {
        "Name": "Freighters",
        "Description": "Industrial-scale cargo transportation ships.",
        "AverageSize": "Huge",
        "AverageCost": "$100 Million",
        "ProcureDiff": 1,
        "Disadvantages": "-3 Engines, -2 Attribute Points",
        "Advantages": "Converted Cargo Bays provide double space. +2 Bays. Capacity 16,000 Units or one size higher. Tech 3 comes with Beam function. 50% repair discount.",
        "Mods": [
            {"Target": "Bays", "Mod": "+2"},
            {"Target": "Engines", "Mod": "-3"},
        ],
    },
    {
        "Name": "Industrial",
        "Description": "Mining and refining factory ships for asteroid mining and colony development.",
        "AverageSize": "Large (Medium - Huge)",
        "AverageCost": "$12 - $108 Million",
        "ProcureDiff": 0,
        "Disadvantages": "-2 Engines, -2 Attribute Points, -3 Bays",
        "Advantages": "Free Industrial Facility and Refinery Facility. Tech 3 comes with Beam function. Free Grapple function.",
        "Mods": [
            {"Target": "Engines", "Mod": "-2"},
            {"Target": "Bays", "Mod": "-3"},
        ],
    },
    {
        "Name": "Shuttles",
        "Description": "Personal transport vehicles suited for station transfers or atmospheric entry.",
        "AverageSize": "Tiny (Diminutive - Small)",
        "AverageCost": "$2 Million",
        "ProcureDiff": 0,
        "Disadvantages": "-2 Structure, -2 Electronics, -1 Hard Points",
        "Advantages": "+4 Engines, +2 Sensors, Basic Auto Pilot (AI +1), +1 Passenger for Diminutive, +2 for Tiny, +3 for Small.",
        "Mods": [
            {"Target": "Engines", "Mod": "+4"},
            {"Target": "Sensors", "Mod": "+2"},
            {"Target": "Structure", "Mod": "-2"},
            {"Target": "Electronics", "Mod": "-2"},
            {"Target": "Hard_Points", "Mod": "-1"},
        ],
    },
]

SHIP_QUIRKS = [
    {
        "Name": "Out Dated",
        "Description": "Old and antiquated; more likely to gain other quirks.",
        "Negative": "Costs 25% less to buy; 50% less to sell. Permanent.",
        "Positive": "Choose another quirk and ignore its negative effect.",
    },
    {
        "Name": "Cranky",
        "Description": "Internal components require physical encouragement to function.",
        "Negative": "If the ship receives 2 Battle Damage in one round, roll for the second damage and add its effect (Base DC 7).",
        "Positive": "None.",
    },
    {
        "Name": "Falling Apart",
        "Description": "A 'pile of junk' with constant maintenance needs.",
        "Negative": "25% reduction in resale value. 20% daily chance of something breaking (1-10% Superficial, 11-80% Minor system/bay problem, 91-100% Major problem).",
        "Positive": "Crew gains Advanced Jerry Rigging feat for repairs to this ship only.",
    },
    {
        "Name": "Infested",
        "Description": "Smelly, annoying space pests living off the ship systems.",
        "Negative": "Daily CON save (DC 12) for all on board or become Nauseated (or Sickened). Engineers take -1 to repair checks.",
        "Positive": "-10 Stealth for stowaways. Advantage to Comms when dealing with pirates/smugglers (who avoid the infestation).",
    },
    {
        "Name": "Bad Past",
        "Description": "The ship is 'wanted' in multiple systems due to previous owners.",
        "Negative": "Disadvantage to Comms in specific situations. People may attack without provocation.",
        "Positive": "50/50 chance a person recognizing the ship will be a friend or foe.",
    },
    {
        "Name": "Artificial Intelligence",
        "Description": "Fully aware AI computer linked to all systems (Highly Illegal).",
        "Negative": "Illegal to sell through official markets. Harsh penalties from authorities.",
        "Positive": "+1 to Sensors, Engines, and Electronics. The ship can drive itself.",
        "Misc": "Possesses a personality: Optimist, Bully, Physio, Shy/Unsure, Overachiever, or Whimsical.",
    },
    {
        "Name": "Noisy",
        "Description": "Constant humming, whizzing, and jittering throughout the bulkheads.",
        "Negative": "-2 for all Boost function rolls.",
        "Positive": "None.",
    },
    {
        "Name": "Battle Scars",
        "Description": "A hull that speaks a thousand words of past adventures and narrow escapes.",
        "Negative": "-1 to Detection DC and +1 to Repair DC for Battle Damage.",
        "Positive": "Advantage to Comms when using Intimidate.",
    },
    {
        "Name": "Lucky",
        "Description": "The ship survives scraps and close calls it shouldn't.",
        "Negative": "None.",
        "Positive": "Once per day, a player can reroll a check that uses one of the ship's Attribute modifiers.",
    },
    {
        "Name": "Cursed",
        "Description": "Things just seem to go wrong when you're aboard this vessel.",
        "Negative": "Once per day, negate the first Critical Success rolled for a ship-based attribute check.",
        "Positive": "None.",
    },
    {
        "Name": "Experimental",
        "Description": "Brand new design with manufacturer kinks not yet worked out.",
        "Negative": "Once per day, roll a d6 (1: Engines, 2: Weapons, 3: Structure, 4: Shields, 5: Electronics, 6: Sensors); attribute drops to 10 until repaired (DC 12 + Tech Level + Hull Size).",
        "Positive": "If the Engineer critically succeeds on repair, bonus to that attribute score equal to their Intelligence modifier.",
    },
]

SPACESHIP_FTL_DRIVES = [
    {
        "Name": "Assisted Jump Drive",
        "TechLevel": 1,
        "DistanceRating": "Medium",
        "WarpFactor": "10+",
        "Price": "$50,000 / 0",
        "Durability": 0,
        "Description": "Works with an external jump gate station to jump at Warp 10 speeds up to Medium distances.",
    },
    {
        "Name": "Warp Drive (The Hopper)",
        "TechLevel": 1,
        "DistanceRating": "Medium",
        "WarpFactor": "1-4",
        "Price": "$150,000 / 0",
        "Durability": 2,
        "Description": "Stretches space-time via positive and negative energy bursts in pulses. Speed: Warp 1-4.",
    },
    {
        "Name": "Assisted Advanced Jump Drive",
        "TechLevel": 2,
        "DistanceRating": "Large",
        "WarpFactor": "10+",
        "Price": "$100,000 / 0",
        "Durability": 0,
        "Description": "Advanced jump drive capable of Long and Extreme jumps with jump gate assistance.",
    },
    {
        "Name": "Warp Drive (The Skimmer)",
        "TechLevel": 2,
        "DistanceRating": "Large",
        "WarpFactor": "1-7",
        "Price": "$300,000 / 0",
        "Durability": 1,
        "Description": "Achieves up to Warp 7 by skimming shrunken space at sub-light speed and bursting at higher frequencies.",
    },
    {
        "Name": "Slip Stream Drive",
        "TechLevel": 2,
        "DistanceRating": "Large",
        "WarpFactor": "1-7",
        "Price": "$450,000 / 1",
        "Durability": 3,
        "Description": "Creates a tear into subspace. Speeds up to Warp 6-7. Takes 30s to make tear, cannot cloak, +4 to enemy tracking.",
    },
    {
        "Name": "Personal Jump Drive",
        "TechLevel": 3,
        "DistanceRating": "Medium (Large with assistance)",
        "WarpFactor": "10+",
        "Price": "$1,000,000 / 0",
        "Durability": 0,
        "Description": "Makes Warp 10 jumps independently up to Medium distances without a jump gate.",
    },
    {
        "Name": "Warp Drive (The High Pulse Drive)",
        "TechLevel": 3,
        "DistanceRating": "Large",
        "WarpFactor": "1-8",
        "Price": "$3,500,000 / 1",
        "Durability": 2,
        "Description": "Near lossless energy teleportation allows high warp frequency transitions up to Warp 8.",
    },
    {
        "Name": "Phase Shift Drive",
        "TechLevel": 3,
        "DistanceRating": "Large",
        "WarpFactor": "1-7",
        "Price": "$5,000,000 / 2",
        "Durability": 6,
        "Description": "Shifts ship out of phase with the universe to accelerate masslessly. Takes 6 seconds (2 turns) to create tear.",
    },
    {
        "Name": "Personal Advanced Jump Drive",
        "TechLevel": 4,
        "DistanceRating": "Large (Extreme with assistance)",
        "WarpFactor": "10+",
        "Price": "$10,000,000 / 1",
        "Durability": 0,
        "Description": "Independent Warp 10 jumps up to Large distances (Extreme with jump gate assistance).",
    },
    {
        "Name": "Expert Warp Drive",
        "TechLevel": 4,
        "DistanceRating": "Extreme",
        "WarpFactor": "1-9",
        "Price": "$15,000,000 / 2",
        "Durability": 3,
        "Description": "Most advanced personal warp device, capable of cruising at speeds up to Warp 9.",
    },
    {
        "Name": "Advanced Slip Stream Drive",
        "TechLevel": 4,
        "DistanceRating": "Extreme",
        "WarpFactor": "1-8",
        "Price": "$25,000,000 / 3",
        "Durability": 8,
        "Description": "Combines Jump Drive, Phase Shift, and Slip Stream Tear. Tears generated within ship in 1 turn; highly stealthy.",
    },
]

SPACECRAFT_HARD_POINTS_AND_BAYS = [
    {
        "Size": "Colossal",
        "WeaponBaySize": "Huge",
        "CustSlotBonus": 3,
        "MilitaryHardPoints": 10,
        "MilitaryBays": 8,
        "CivilianHardPoints": 8,
        "CivilianBays": 10,
    },
    {
        "Size": "Gargantuan",
        "WeaponBaySize": "Huge",
        "CustSlotBonus": 2,
        "MilitaryHardPoints": 9,
        "MilitaryBays": 7,
        "CivilianHardPoints": 7,
        "CivilianBays": 9,
    },
    {
        "Size": "Huge",
        "WeaponBaySize": "Large",
        "CustSlotBonus": 2,
        "MilitaryHardPoints": 8,
        "MilitaryBays": 5,
        "CivilianHardPoints": 6,
        "CivilianBays": 8,
    },
    {
        "Size": "Large",
        "WeaponBaySize": "Large",
        "CustSlotBonus": 2,
        "MilitaryHardPoints": 7,
        "MilitaryBays": 4,
        "CivilianHardPoints": 5,
        "CivilianBays": 7,
    },
    {
        "Size": "Medium",
        "WeaponBaySize": "Medium",
        "CustSlotBonus": 1,
        "MilitaryHardPoints": 6,
        "MilitaryBays": 3,
        "CivilianHardPoints": 4,
        "CivilianBays": 6,
    },
    {
        "Size": "Small",
        "WeaponBaySize": "Medium",
        "CustSlotBonus": 1,
        "MilitaryHardPoints": 6,
        "MilitaryBays": 2,
        "CivilianHardPoints": 4,
        "CivilianBays": 5,
    },
    {
        "Size": "Tiny",
        "WeaponBaySize": "Small",
        "CustSlotBonus": 1,
        "MilitaryHardPoints": 5,
        "MilitaryBays": 1,
        "CivilianHardPoints": 3,
        "CivilianBays": 4,
    },
    {
        "Size": "Diminutive",
        "WeaponBaySize": "Small",
        "CustSlotBonus": 0,
        "MilitaryHardPoints": 3,
        "MilitaryBays": 0,
        "CivilianHardPoints": 2,
        "CivilianBays": 2,
    },
    {
        "Size": "Fine",
        "WeaponBaySize": "Small",
        "CustSlotBonus": 0,
        "MilitaryHardPoints": 2,
        "MilitaryBays": 0,
        "CivilianHardPoints": 1,
        "CivilianBays": 1,
    },
]

SHIP_WEAPON_TYPES = [
    {
        "Name": "Projectile",
        "DamageType": "Kinetic",
        "Range": "Infinite",
        "AmmoCapacity": 6,
        "Bonus": "Standard kinetic shell attack.",
        "ClassBonus": "+1 round per Class. At Class 3, gains Burst Fire (reroll failed d10s consuming ammo).",
        "BaseCosts": {
            "Small": 80000,
            "Medium": 320000,
            "Large": 1280000,
            "Huge": 2560000,
        },
        "AmmoCosts": {
            "Small": 1600,
            "Medium": 6400,
            "Large": 25600,
            "Huge": 102400,
        },
    },
    {
        "Name": "Laser",
        "DamageType": "Thermal",
        "Range": "Long",
        "AmmoCapacity": "Infinite (requires Engines/Electronics >= 7)",
        "Bonus": "+1 to d10. Each shot lowers ship Detection DC by 1 next round.",
        "ClassBonus": "Class 1: Point defense (-1 penalty); Class 2: +2 to d10; Class 3: Overheat (+1 bonus d10); Class 4: +3 to d10; Class 5: Point defense without penalty.",
        "BaseCosts": {
            "Small": 156250,
            "Medium": 625000,
            "Large": 1250000,
            "Huge": 5000000,
        },
        "AmmoCosts": {
            "Small": 52000,
            "Medium": 208350,
            "Large": 833350,
            "Huge": 3333350,
        },
    },
    {
        "Name": "Plasma",
        "DamageType": "Thermal",
        "Range": "Small, Medium",
        "AmmoCapacity": 4,
        "Bonus": "Reroll 1s at Small range (loses bonus at Medium).",
        "ClassBonus": "Masterwork costs 3x. Class 1: +1 to d10; Class 2: Long range; Class 3: Reroll 1s at Small & Medium; Class 4: Exploding 9s and 10s; Class 5: Reroll 1s and 2s.",
        "BaseCosts": {
            "Small": 234375,
            "Medium": 937500,
            "Large": 1875000,
            "Huge": 6500000,
        },
        "AmmoCosts": {
            "Small": 4700,
            "Medium": 18750,
            "Large": 75000,
            "Huge": 300000,
        },
    },
    {
        "Name": "Missile",
        "DamageType": "Payload Dependent",
        "Range": "Ammo Dependent",
        "AmmoCapacity": 3,
        "Bonus": "Ammo Dependent",
        "ClassBonus": "Even classes: +1 Ammo capacity; Class 1: +1 d10 vs ships 2 sizes smaller; Class 3: +1 d10 vs swarms; Class 5: Burst Fire.",
        "BaseCosts": {
            "Small": 195300,
            "Medium": 590625,
            "Large": 3125000,
            "Huge": 6250000,
        },
        "AmmoCosts": {
            "Small": 3900,
            "Medium": 15625,
            "Large": 62500,
            "Huge": 250000,
        },
    },
]

SHIP_BAYS = [
    {
        "Name": "Cargo Bay",
        "BasePrice": "$20,000 (Small, doubles per size up)",
        "SizeRequirement": "None",
        "Description": "Increases Cargo Capacity by 1/2 the base units of the ship's size. Can be reinforced for hazardous materials.",
    },
    {
        "Name": "Science Bay",
        "BasePrice": "$15,000 (triples per class level)",
        "SizeRequirement": "Small+",
        "Description": "Acts as Chemical and Electronic Kit (+X crafting bonus where X = Class level).",
    },
    {
        "Name": "Medical Bay",
        "BasePrice": "$25,000",
        "SizeRequirement": "Tiny+",
        "Description": "Equipped with Medical & Surgical Kit. +2 bonus to Medical treatment actions. Class 3 allows resuscitation.",
    },
    {
        "Name": "Medical Facility",
        "BasePrice": "$500,000",
        "SizeRequirement": "Large+ (takes 2 Bays, or 1 Bay on Gargantuan/Colossal)",
        "Description": "Multi-patient care facility. +4 bonus to Medical skill, doubles as Pharmacy Kit.",
    },
    {
        "Name": "Industrial Bay",
        "BasePrice": "$15,000 (triples per class level)",
        "SizeRequirement": "Tiny+",
        "Description": "Acts as Chemical and Mechanical Kit (+1/2 level Chemical, +1/level Mechanical crafting).",
    },
    {
        "Name": "Industrial Facility",
        "BasePrice": "$250,000 (triples per class level)",
        "SizeRequirement": "Large+ (takes 2 Bays, or 1 Bay on Gargantuan/Colossal)",
        "Description": "Multi-worker facility providing +1/2 level bonus to repairing Battle Damage.",
    },
    {
        "Name": "Engineering Bay",
        "BasePrice": "$30,000 (triples per class level)",
        "SizeRequirement": "Tiny+",
        "Description": "Electronics and Mechanical Kit (+1 per level to both). Allows characters to actively make modifications during combat.",
    },
    {
        "Name": "Engineering Facility",
        "BasePrice": "$500,000 (triples per class level)",
        "SizeRequirement": "Large+ (takes 2 Bays, or 1 Bay on Gargantuan/Colossal)",
        "Description": "Multi-worker engineering space providing +1 per level bonus to repairs on this ship.",
    },
    {
        "Name": "Astrometrics Bay",
        "BasePrice": "$25,000 (triples per class level)",
        "SizeRequirement": "Tiny+",
        "Description": "Doubles sensor range. +1 per Class to Sensor scans of celestial objects; +1/2 per Class for scanning stealth ships.",
    },
    {
        "Name": "Refinery Bay",
        "BasePrice": "$35,000 (doubles per size & class)",
        "SizeRequirement": "Tiny+",
        "Description": "Refines raw materials/salvage (50% weight/size reduction). 100 units/day per Class.",
    },
    {
        "Name": "Refinery Facility",
        "BasePrice": "$200,000 (doubles per size & class)",
        "SizeRequirement": "Large+",
        "Description": "High-volume refinery processing 500 units/day + 150 per Class level.",
    },
    {
        "Name": "Docking Bay",
        "BasePrice": "$10,000 (Small, doubles per size up)",
        "SizeRequirement": "Small+",
        "Description": "Docks ships 2 sizes smaller. Combined bays accommodate larger or multiple smaller craft.",
    },
    {
        "Name": "Passenger Bay",
        "BasePrice": "$20,000 (Small, doubles per size up)",
        "SizeRequirement": "Tiny+",
        "Description": "Increases living capacity by base size amount. Luxury version costs 2x for half capacity; Cramped carries 2x.",
    },
    {
        "Name": "Detention Bay",
        "BasePrice": "$15,000 (Small, doubles per size up)",
        "SizeRequirement": "Tiny+",
        "Description": "Secure containment brig. +5 DC on escape/hacking attempts. Can double as 1/2 passenger bay.",
    },
    {
        "Name": "Hydroponics Bay",
        "BasePrice": "$20,000 (Small, doubles per size up)",
        "SizeRequirement": "Small+",
        "Description": "Extends life support duration by 50%. +2 to crafting chemical/pharmaceutical organic items.",
    },
    {
        "Name": "Armory",
        "BasePrice": "$25,000 (Small, doubles per size up)",
        "SizeRequirement": "Tiny+",
        "Description": "Biometric weapons vault. Equip ground combat gear as Move Action; +2 to maintain/repair personal ground gear.",
    },
    {
        "Name": "Electronic Intelligence (ELINT) Center",
        "BasePrice": "$30,000 (Small, doubles per size up)",
        "SizeRequirement": "Medium+",
        "Description": "Dedicated cyberwarfare room. +2 to Hacking, Jamming, and Counter-Hacking. Enables and supports Crypto.",
    },
    {
        "Name": "Recreation Bay",
        "BasePrice": "$15,000 (Small, doubles per size up)",
        "SizeRequirement": "Small+",
        "Description": "Crew relaxation bay. Recover from Shaken/Fatigued in half time; +1 morale bonus to Will saves & Initiative for 24h.",
    },
]

SHIP_FUNCTION_UPGRADES = [
    {
        "Name": "Transporter Bay (Beam)",
        "Function": "Beam",
        "SlotRequired": "1 Bay (Customization point not valid)",
        "BasePrice": "$100,000 (Small, +$100k per size/class)",
        "SizeRequirement": "Small+",
        "Description": "Enables Beam function. Class 0: Bay-to-Bay (4 people). Class 1: Anywhere to/from Bay. Class 2: Site-to-site. Shield penetration DC: 12 + target Shields Mod.",
    },
    {
        "Name": "Cloaking Device (Cloak)",
        "Function": "Cloak",
        "SlotRequired": "1 Hard Point & 1 Bay (one can be Cust. point)",
        "BasePrice": "$200,000 (Tiny, +$200k per size/class)",
        "SizeRequirement": "Tiny+",
        "Description": "Improves Detection DC (+3 at Class 0, +2 per class). Shields disabled while active. Firing weapons reduces stealth temporarily.",
    },
    {
        "Name": "Crypto Computer (Crypto)",
        "Function": "Crypto",
        "SlotRequired": "1 Bay or 1 Cust. Point",
        "BasePrice": "$50,000 (Tiny, +$50k per size/class)",
        "SizeRequirement": "Tiny+",
        "Description": "Enables Crypto function for secret transmissions and drone link encryption. +1 bonus per class above 0.",
    },
    {
        "Name": "Jammer (Jam)",
        "Function": "Jam",
        "SlotRequired": "1 Hard Point",
        "BasePrice": "$50,000 (Tiny, +$50k per size/class)",
        "SizeRequirement": "Tiny+",
        "Description": "Enables Jam function to intercept or disrupt communications, hacking attempts, drones, or enemy sensor arrays.",
    },
    {
        "Name": "Grappler (Grapple)",
        "Function": "Grapple",
        "SlotRequired": "1 Hard Point",
        "BasePrice": "$50,000 (Tiny, +$50k per size/class)",
        "SizeRequirement": "Tiny+",
        "Description": "Enables Grapple function to latch onto, tow, or restrain target vessels.",
    },
]

SHIP_ATTRIBUTE_UPGRADES = {
    "Description": "Upgrades improve Core System Attributes from Class 0 to 5. Each Class adds base cost again; Masterworked doubles final cost and adds +1 score per class level. Requires 1 Customization Point (or converted HP / Bay).",
    "BaseCosts": {
        "Engines": {
            "Fine": 50000,
            "Diminutive": 100000,
            "Tiny": 150000,
            "Small": 200000,
            "Medium": 250000,
            "Large": 300000,
            "Huge": 350000,
            "Gargantuan": 400000,
            "Colossal": 450000,
        },
        "Weapons": {
            "Fine": 50000,
            "Diminutive": 100000,
            "Tiny": 150000,
            "Small": 200000,
            "Medium": 250000,
            "Large": 300000,
            "Huge": 350000,
            "Gargantuan": 400000,
            "Colossal": 450000,
        },
        "Structure": {
            "Fine": 45000,
            "Diminutive": 90000,
            "Tiny": 135000,
            "Small": 180000,
            "Medium": 225000,
            "Large": 270000,
            "Huge": 315000,
            "Gargantuan": 360000,
            "Colossal": 405000,
        },
        "Shields": {
            "Fine": 60000,
            "Diminutive": 120000,
            "Tiny": 180000,
            "Small": 240000,
            "Medium": 300000,
            "Large": 360000,
            "Huge": 420000,
            "Gargantuan": 480000,
            "Colossal": 540000,
        },
        "Electronics": {
            "Fine": 60000,
            "Diminutive": 120000,
            "Tiny": 180000,
            "Small": 240000,
            "Medium": 300000,
            "Large": 360000,
            "Huge": 420000,
            "Gargantuan": 480000,
            "Colossal": 540000,
        },
        "Sensors": {
            "Fine": 40000,
            "Diminutive": 80000,
            "Tiny": 120000,
            "Small": 160000,
            "Medium": 200000,
            "Large": 240000,
            "Huge": 280000,
            "Gargantuan": 320000,
            "Colossal": 360000,
        },
    },
}

SHIP_ACCESSORIES = [
    {
        "Name": "Warp Field Expander",
        "SlotRequired": "1 HP & 1 Bay",
        "BaseCost": "$450,000",
        "Summary": "Allows a ship with Warp Drive FTL to expand their warp field around another ship to travel together at identical speed.",
    },
    {
        "Name": "Jump Assistance Drive",
        "SlotRequired": "1 HP & 1 Bay",
        "BaseCost": "$30,000",
        "Summary": "Allows a ship with a Personal Jump Drive to assist another ship as if functioning as a localized Jump Gate.",
    },
    {
        "Name": "Shield Extender",
        "SlotRequired": "1 Bay",
        "BaseCost": "$1,500,000",
        "Summary": "Allows a ship to manipulate and project its shields to envelop and protect adjacent allied craft.",
    },
    {
        "Name": "Shield Enhancer",
        "SlotRequired": "1 HP",
        "BaseCost": "$600,000",
        "Summary": "Provides +1 Reflector value and +1 Shield-based DR to defensive shields.",
    },
    {
        "Name": "Phase Discriminator",
        "SlotRequired": "1 HP",
        "BaseCost": "$500,000",
        "Summary": "Grants bonuses on Scan functions when searching for ships operating Out of Phase.",
    },
    {
        "Name": "Plasma Flow Enhancer",
        "SlotRequired": "1 Bay",
        "BaseCost": "$200,000",
        "Summary": "+1 to Warp speed (up to maximum Warp 10).",
    },
    {
        "Name": "Engine Boosters",
        "SlotRequired": "1 HP or 1 Customization Slot",
        "BaseCost": "$250,000",
        "Summary": "Passive sub-light thrusters providing +2 on active Pilot checks using Engines (e.g. Close/Widen, Evasive Thrusters).",
    },
    {
        "Name": "Drone Controller",
        "SlotRequired": "1 HP & 1 Bay",
        "BaseCost": "$500,000",
        "Summary": "Hardware interface and receiver required for launching, directing, and linking remote drones.",
    },
    {
        "Name": "Reactor Auxiliary Capacitor",
        "SlotRequired": "1 Customization Slot",
        "BaseCost": "$150,000",
        "Summary": "Reserve energy storage; +2 bonus on Craft checks to Overclock Core, and absorbs failed overclock backcharges.",
    },
    {
        "Name": "Holographic Decoy Launcher",
        "SlotRequired": "1 HP",
        "BaseCost": "$120,000",
        "Summary": "Projector for chaff and holographic signatures. +2 on Electronics checks; incoming guided missiles suffer 75% miss chance.",
    },
    {
        "Name": "Fire-Control Matrix",
        "SlotRequired": "1 HP or 1 Customization Slot",
        "BaseCost": "$300,000",
        "Summary": "Advanced targeting computer. Grants +1 to attack d10s and eliminates the -2 penalty when using Defensive Fire.",
    },
    {
        "Name": "Hull Nanite Repair Pods",
        "SlotRequired": "1 Customization Slot",
        "BaseCost": "$400,000",
        "Summary": "External nano-welder pods. Allows Repair checks to be made as a Move Action or grants a +2 bonus.",
    },
    {
        "Name": "Advanced Recycler Grid",
        "SlotRequired": "1 Customization Slot",
        "BaseCost": "$80,000",
        "Summary": "Atmospheric/water recycler. Increases default passenger capacity by 25% and grants +2 to saves against infestations/toxins.",
    },
]


def init_spaceship_reference_tables(db_conn=None):
    if db_conn is None:
        db_conn = get_reference_db()
    if db_conn is None:
        return None

    tables_data = {
        "spaceship_hull_sizes": HULL_SIZES,
        "spaceship_hull_configurations": HULL_CONFIGURATIONS,
        "spaceship_quirks": SHIP_QUIRKS,
        "spaceship_ftl_drives": SPACESHIP_FTL_DRIVES,
        "spaceship_hard_points_and_bays": SPACECRAFT_HARD_POINTS_AND_BAYS,
        "spaceship_weapon_types": SHIP_WEAPON_TYPES,
        "spaceship_bays": SHIP_BAYS,
        "spaceship_function_upgrades": SHIP_FUNCTION_UPGRADES,
        "spaceship_attribute_upgrades": [SHIP_ATTRIBUTE_UPGRADES],
        "spaceship_accessories": SHIP_ACCESSORIES,
    }

    for table_name, data in tables_data.items():
        try:
            existing = list(db_conn.find(collection=table_name))
            if not existing:
                db_conn.insertMany(data, collection=table_name)
            elif table_name == "spaceship_hull_configurations":
                if any("Mods" not in doc for doc in existing if isinstance(doc, dict)):
                    try:
                        db_conn.drop(collection=table_name)
                    except Exception:
                        pass
                    db_conn.insertMany(data, collection=table_name)
        except Exception as e:
            log.error(f"Error initializing spaceship table {table_name}: {e}")

    return db_conn
